[pytest]
;python_functions = t_*
;python_files = tf_*
;python_classes = TSuite_*
markers:
    regression: all tests related to regression suite
    smoke: all tests related to regression suite
    string_operations: all tests related to strings
    math_operations: all tests related to math_operations
log_cli = true
log_cli_level=INFO

